"""Proper OnDelete settings (4)

Revision ID: aa300222e1f7
Revises: 399aa4e5a4df
Create Date: 2024-11-16 14:43:11.172368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa300222e1f7'
down_revision: Union[str, None] = '399aa4e5a4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
